config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user, only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]

  def new
  end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:blue] = "Email sent with password reset instruction"
      redirect_to root_url
    else
      flash.now[:red] = "Email adress not found"
      render 'new'
    end
  end

  def edit
  end

  def update
    if params[:user][:password].empty?
      @user.errors.add(:password, "can't be empty")
      render 'edit'
    elsif @user.update_attributes(user_params)
      flash[:green] = "Password has been reset."
      redirect_to login_url
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def get_user
    @user = User.find_by(email: params[:email])
  end

  #confirm valid user
  def valid_user
    unless (@user && @user.activated? && @user.authenticated?(:reset, params[:id]))
      redirect_to root_url
    end
  end

  # checks expiration token
  def check_expiration
    if @user.password_reset_expired?
      flash[:red] = "Password reset has expired."
      redirect_to new_password_reset_url
    end
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title, "Reset password") %>

<div class="row">
  <div class="col s12 m6 offset-m3">
    <h2 class="center-align">Reset password</h2>
    <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= hidden_field_tag :email, @user.email %>

      <div class="input-field col s12 m6 offset-m3">
        <%= f.password_field :password %>
        <%= f.label :password %>
      </div>
      <div class="input-field col s12 m6 offset-m3">
        <%= f.password_field :password_confirmation %>
        <%= f.label :password_confirmation, "Confirmation" %>
      </div>

      <div class="col s12 m6 offset-m3">
        <div class="center-align">
          <%= f.button type: "submit", name: "action", class: "btn btn-large waves-effect waves-light blue white-text" do %>
            Update password<i class="material-icons right">keyboard_tab</i>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<% provide(:title, "Forgot password") %>

<div class="row">
  <div class="col s12 m6 offset-m3">
    <h2 class="center-align">Forgot password</h2>
    <%= form_for(:password_reset, url: password_resets_path) do |f| %>
      <div class="input-field col s12 m6 offset-m3">
        <%= f.email_field :email %>
        <%= f.label :email %>
        <span class="helper-text" data-error="wrong" data-success="right"></span>
      </div>
      <div class="col s12 m6 offset-m3">
        <div class="center-align">
          <%= f.button type: "submit", name: "action", class: "btn btn-large waves-effect waves-light blue white-text" do %>
            Submit<i class="material-icons right">keyboard_tab</i>
          <% end %>
          <p>New user? <%= link_to "Sign up now!", signup_path %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>