config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
      <div class="card-panel red lighten-5 red-text text-darken-4">
        I've found errors
        <span class="new badge red"><%= pluralize(object.errors.count, "error") %></span>
      </div>
      <ul class="with_dot">
        <% object.errors.full_messages.each do |msg| %>
        <li class="red-text"><%= msg %></li>
        <% end %>
      </ul>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items, renderer: MaterializeRenderer, class: "center-align pagination" %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="input-field col s12">
    <%= f.text_area :content, placeholder: "Your post...", class: "materialize-textarea", id: "textarea1", data: { "length" => "255" } %>
    <%= f.label :content %>
  </div>

  <div class="file-field input-field col s12">
    <div class="btn blue">
      <span>File</span>
      <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png,image/ico' %>
    </div>
    <div class="file-path-wrapper">
      <input class="file-path validate" type="text" placeholder="Upload your photo">
    </div>
  </div>

    <%= f.button type: "submit", name: "action", class: "btn btn-large waves-effect waves-light blue white-text" do %>
      Post <i class="material-icons right">check</i>
    <% end %>

<% end %>

<script type="text/javascript">
  $(#micropost_picture).bind('change', function() {
      var size_in_megabytes = this.files[0].size/1024/1024;
      if (size_in_megabytes > 5) {
          alert('Maximum file size is 5MB. Please choose a smaller file.');
      }
  });
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
  <a href="<%= following_user_path(@user) %>"> <%= @user.following.count %> following </a>
  <a href="<%= followers_user_path(@user) %>"> <%= pluralize(@user.followers.count, "follower") %></a>

app/views/shared/_user_basic.html.erb
<div class="marginBottom">
  <%= link_to gravatar_for(current_user, size: 50), current_user, class: "avatar" %>
  <span class="blue-grey-text"><%= current_user.name %>, <%= link_to "view my profile", current_user %></span>
</div>

app/views/shared/_user_info.html.erb
<div class="card-panel blue-grey lighten-5 marginTop center-align">
  <h3 class="blue-grey-text" style="margin-bottom: 15px"><%= @user.name %></h3>
  <div class="col s12">
    <%= link_to gravatar_for(@user), edit_user_path(current_user)%>
  </div>
  <div class="col s12">
    <p><%= @user.email %></p>
  </div>
  <div class="col s12 marginBottom">
    With us for: <%= @user.activated_at.strftime("%B %Y") %><br>
    <%= pluralize(current_user.microposts.count, "micropost") %>
  </div>
  <% unless current_user?(@user) %>
  <div class="col s12 marginBottom">
    <%= render 'users/follow_form' if logged_in? %>
  </div>
  <% end %>
  <div class="stats center-align">
    <%= render 'shared/stats' %>
  </div>
</div>