config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="page-footer blue">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Social Posts</h5>
        <p class="grey-text text-lighten-4">Get all your posts in one place - very simple application to write posts for your friends</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
          <ul>
            <li><%= link_to "Sign up",   signup_path, class: 'grey-text text-lighten-3' %></li>
            <li><%= link_to "Log in",   login_path, class: 'grey-text text-lighten-3' %></li>
            <li><%= link_to "Help",   help_path, class: 'grey-text text-lighten-3' %></li>
            <li><%= link_to "Contact", contact_path, class: 'grey-text text-lighten-3' %></li>
          </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      © 2018 Copyright by Kamil Pikula
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar-fixed">
  <nav>
    <div class="nav-wrapper blue">
      <div class="container">
        <%= link_to "Social Posts", root_path, id: "logo", class: "brand-logo" %>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <%= render 'layouts/nav' %>
        <!-- TEST MOBILE NAV -->
        <%= render 'layouts/nav_mobile' %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_nav.html.erb
<ul class="right hide-on-med-and-down">
  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to "Help", help_path %></li>
  <% if logged_in? %>
    <!-- Dropdown Trigger -->
    <li><%= link_to "Users", users_path %></li>
    <li>
      <%= link_to '#', class: "dropdown-trigger", 'data-target': "dropdown1" do %>
        Account<i class="material-icons right">arrow_drop_down</i>
      <% end %>
    </li>

    <!-- Dropdown Structure -->
    <ul id='dropdown1' class='dropdown-content'>
      <li><%= link_to "My profile", current_user, class: "blue-text" %></li>
      <li><%= link_to "Settings", edit_user_path(current_user), class: "blue-text" %></li>
      <li class="divider" tabindex="-1"></li>
      <li><%= link_to "Log out", logout_path, class: "blue-text", method: :delete %></li>
    </ul>
  <% else %>
    <li><%= link_to "Log in", login_path %></li>
  <% end %>
</ul>

app/views/layouts/_nav_mobile.html.erb
<ul class="sidenav" id="mobile-demo">
  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to "Help", help_path %></li>
  <% if logged_in? %>
    <li><%= link_to "Users", users_path %></li>
    <li class="divider" tabindex="-1"></li>
    <li><%= link_to "My profile", current_user %></li>
    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
    <li><%= link_to "Log out", logout_path, method: :delete %></li>
  <% else %>
    <li><%= link_to "Log in", login_path %></li>
  <% end %>
</ul>

app/views/layouts/_rails_default.html.erb
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta name="theme-color" content="#2196F3">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'https://fonts.googleapis.com/icon?family=Material+Icons' %>
    <%= stylesheet_link_tag    'https://fonts.googleapis.com/css?family=Montserrat:200,400,700' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_scripts.html.erb
<%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% if logged_in? %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "card-panel #{message_type} lighten-4 #{message_type}-text text-darken-4") %>
      <% end %>
      <%= yield %>
    </div>
    <% else %>
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "card-panel #{message_type} lighten-4 #{message_type}-text text-darken-4") %>
    <% end %>
        <%= yield %>
    <% end %>
    <%= render 'layouts/footer' %>
    <!--<#%= debug(params) if Rails.env.development? %> -->
    <%= render 'layouts/scripts' %>
  </body>
</html>